server {
    listen 80;
    server_name localhost;

    location /test {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    location /test/ {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # Serve static assets correctly
    location /test/static/ {
        root /usr/share/nginx/html;
    }
}
