version: "3.8"

services:
  backend-test:
    container_name: zorzon_backend_test
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    platform: linux/arm64
    volumes:
      - strapi_test_media:/app/public/uploads
    ports:
      - "1337:1337"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_HOST: zorzon_db_test
      NODE_ENV: development
      URL: https://test-admin.zorzon.com.ro
      TRUST_PROXY: true
    depends_on:
      - db-test
    networks:
      - zorzon_test

  frontend-test:
    container_name: zorzon_frontend_test
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    platform: linux/arm64
    volumes:
      - ./frontend:/app
      - ./frontend/.env:/opt/app/.env

    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
    restart: unless-stopped
    depends_on:
      - backend-test
    networks:
      - zorzon_test

  ar-viewer-test:
    container_name: zorzon_arviewer_test
    build:
      context: ./ar-viewer
      dockerfile: Dockerfile.test
    platform: linux/arm64
    volumes:
      - ./ar-viewer:/app
      - /app/node_modules
      - ./ar-viewer/.env:/opt/app/.env
    ports:
      - "5174:5174"
    environment:
      NODE_ENV: development
    restart: unless-stopped
    depends_on:
      - backend-test
    networks:
      - zorzon_test

  db-test:
    container_name: zorzon_db_test
    image: postgres:15
    platform: linux/arm64
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi_test
    ports:
      - "5432:5432"
    networks:
      - zorzon_test

volumes:
  postgres_test_data:
  strapi_test_media:
  caddy_test_data:
  caddy_test_config:

networks:
  zorzon_test:
    driver: bridge
  zorzon:
    external: true
