services:
  backend:
    container_name: zorzon_backend
    build:
      context: .backend
      dockerfile: ./backend/Dockerfile.prod
    platform: linux/amd64 #for platform error on Apple M1 chips
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "1338:1337" # After rev proxy caddy do port exposed for internal communication
    env_file:
      - ./backend/.env
    environment:
      DATABASE_HOST: zorzon_db
      NODE_ENV: production # Ensure it's running in production mode
    depends_on:
      - db
    networks:
      - zorzon

  frontend:
    container_name: zorzon_frontend
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile.prod
    platform: linux/arm64 # Ensuring compatibility with ARM-based systems
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/.env:/opt/app/.env
    ports:
      - "5174:5173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - zorzon
    depends_on:
      - backend

  db:
    container_name: zorzon_db
    image: postgres:15
    platform: linux/amd64 #for platform error on Apple M1 chips
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d # Mount backup directory to init scripts
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    networks:
      - zorzon

volumes:
  postgres_data:

networks:
  zorzon:
    driver: bridge
