services:
  caddy:
    image: caddy:latest
    container_name: caddy
    platform: linux/arm64 # Ensuring compatibility with ARM-based systems
    networks:
      - zorzon
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # Your Caddyfile configuration
      - caddy_data:/data # Persistent storage for SSL certificates
      - caddy_config:/config # Caddy configuration data

  backend:
    container_name: zorzon_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    platform: linux/arm64 #for platform error on Apple M1 chips
    volumes:
      - strapi_media:/app/public/uploads # Persistent storage for media library
    expose:
      - "1338" # Port exposed for internal communication
    env_file:
      - ./backend/.env
    environment:
      DATABASE_HOST: zorzon_db
      NODE_ENV: production # Ensure it's running in production mode
      URL: https://admin.zorzon.com.ro # The URL of your Strapi backend
      TRUST_PROXY: true # Make sure Strapi trusts the reverse proxy, as a string
    depends_on:
      - db
    networks:
      - zorzon

  frontend:
    container_name: zorzon_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    platform: linux/arm64 # Ensuring compatibility with ARM-based systems
    volumes:
      - ./frontend:/app
      - ./frontend/.env:/opt/app/.env
    expose:
      - "80" # Port exposed for internal communication
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - zorzon
    depends_on:
      - backend

  db:
    container_name: zorzon_db
    image: postgres:15
    platform: linux/arm64 #for platform error on Apple M1 chips
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d # Mount backup directory to init scripts
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - "5433:5432"
    networks:
      - zorzon

volumes:
  postgres_data:
  strapi_media: # Add this to declare the strapi_media volume
  caddy_data:
  caddy_config:

networks:
  zorzon:
    driver: bridge
  zorzon2-test_zorzon_test:
    external: true
