# frontend/Dockerfile for Production
FROM node:18-bullseye AS production

WORKDIR /app

ENV NODE_ENV=production

COPY backend/package.json backend/package-lock.json ./
RUN npm install --production

COPY . .

RUN npm run build

EXPOSE 1338

CMD ["npm", "run", "start"]