# frontend/Dockerfile for Production
FROM node:18-alpine AS builder

WORKDIR /app

ENV NODE_ENV=production

COPY package.json package-lock.json ./
RUN npm install --production

COPY . .

RUN npm run build

EXPOSE 1338

CMD ["npm", "run", "start"]