# backend/Dockerfile
FROM --platform=linux/amd64 node:18-alpine AS development


WORKDIR /app

# Copy package files
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY backend/ ./

# Expose port used by Strapi
EXPOSE 1338

# Run Strapi in development mode
CMD ["npm", "run", "develop"]
