# backend/Dockerfile
FROM --platform=linux/amd64 node:18-alpine AS development

# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /app

# Copy package files
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY backend/ ./

# Expose port used by Strapi
EXPOSE 1338

# Run Strapi in development mode
CMD ["npm", "run", "develop"]
